title: Sofia Atlas
description: Данни и визуализации за пазара на жилища и сградите в София.
lang: bg
url: https://s7oev.com
baseurl: /sofia-atlas
permalink: pretty
markdown: kramdown
theme: null
collections:
  price_news:
    output: true
    permalink: /prices/news/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image_root: ""
      body_class: ""
  - scope:
      path: ""
      type: price_news
    values:
      layout: news-article
